from Bio.pairwise2 import *
from Bio.SubsMat import MatrixInfo as matlist
import random

matrix = matlist.blosum62

seq1 = "VLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRFKHLKTEAEMKASEDLKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHPGDFGADAQGAMNKALELFRKDIAAKYKELGYQG"

seq2 = "GLSDGEWQLVLNVWGKVEADVAGHGQEVLIRLFKGHPETLEKFDKFKHLKSEDEMKASEDLKKHGNTVLTALGGILKKKGHHEAELTPLAQSHATKHKIPVKYLEFISEAIIQVLQSKHPGDFGADAQGAMSKALELFRNDMAAKYKELGFQG"

seq3 = "GSMNPPPPETSNPNKPKRQTNQLQYLLRVVLKTLWKHQFAWPFQQPVDAVKLNLPDYYKIIKTPMDMGTIKKRLENNYYWNAQECIQDFNTMFTNCYIYNKPGDDIVLMAEALEKLFLQKINELPTEE"

for a in align.globaldx(seq1, seq2, matrix):
        print(format_alignment(*a))

for a in align.globaldx(seq2, seq3, matrix):
        print(format_alignment(*a))

for a in align.globaldx(seq1, seq3, matrix):
        print(format_alignment(*a))
        
hSCOTIN = "MTAPVPAPRILLPLLLLLLLTPPPGARGEVCMASRGLSLFPESCPDFCCGTCDDQYCCSDVLKKFVWSEERCAVPEASVPASVEPVEQLGSALRFRPGYNDPMSGFGATLAVGLTIFVLSVVTIIICFTCSCCCLYKTCRRPRPVVTTTTSTTVVHAPYPQPPSVPPSYPGPSYQGYHTMPPQPGMPAAPYPMQYPPPYPAQPMGPPAYHETLAGGAAAPYPASQPPYNPAYMDAPKAAL"
mSCOTIN = "MAAPAPSLWTLLLLLLLLPPPPGAHGELCRPFGEDNSIPVFCPDFCCGSCSNQYCCSDVLRKIQWNEEMCPEPESSRFSTPAEETPEHLGSALKFRSSFDSDPMSGFGATVAIGVTIFVVFIATIIICFTCSCCCLYKMCCPQRPVVTNTTTTTVVHAPYPQPQPQPVAPSYPGPTYQGYHPMPPQPGMPAAPYPTQYPPPYLAQPTGPPPYHESLAGASQPPYNPTYMDSLKTIP"

for a in align.globaldx(hSCOTIN, mSCOTIN, matrix):
        print(format_alignment(*a))

import os
os.getcwd() ## 파일이 생성되는 path

aa_list = ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V']
choicelist = [random.choice(aa_list) for i in range(500)] ## create reandom sequence, range 500
a=''
for choice in choicelist:
        a = a + choice

with open ('./random_seq.txt', 'w') as f: ## 자원을 획득하고 사용 직후 반납하는 문법
        f.write(a)
